name: Build Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the image"
        required: true
        default: "latest"

run-name: Build image ${{ inputs.version }}

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      REGISTRY: univer-acr-eastus-registry.us-east-1.cr.aliyuncs.com
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          region-id: cn-shenzhen
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/devops/codex-trace:${{ inputs.version }}
            ${{ env.REGISTRY }}/devops/codex-trace:buildcache
          cache-from: type=registry,ref=${{ env.REGISTRY }}/devops/codex-trace:buildcache
          build-args: BUILDKIT_INLINE_CACHE=1
