name: Build Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the image"
        required: true
        default: "latest"

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      REGISTRY: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          region-id: cn-shenzhen
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/devops/codex-trace:${{ inputs.version }}
          cache-from: type=gha,scope=codex-trace
          cache-to: type=gha,mode=max,scope=codex-trace
